### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by ktakattack** [csr/discord-coffee-buddy#4]

**Comment by tayoogunbiyi** [comment]
@ktakattack @csr @smartclash  We probably want to add a nice looking screenshot of the bot welcoming 2 users in the `README.md` file. I would have made a screenshot right now to include it, but we don't have an official bot yet.  I don't want a bot with the name `test-bot` to end up in the readme :)

**Comment by csr** [comment]
Great idea! Yes, for sure. I think we should do this tomorrow once things are finalized.
