### ISSUE TITLE
private channel creation

### ISSUE THREAD

**Issue by ktakattack** [csr/discord-coffee-buddy#6]
Create private channel under the same category, but are private to the 2 buddies and the bot.

**Comment by smartclash** [comment]
We should be creating two channels. One is for the text and the other one would be for voice. The question is what do we name it. It should be either for these two:

- username1-username2
- randomword1-randomword2

Having a static name for every channel is easy but it might be freaking hard for the admin to manage and moderate 100s of channels being created every week.

What's your thought on this @csr ?
