### ISSUE TITLE
DB integration

### ISSUE THREAD

**Issue by ktakattack** [csr/discord-coffee-buddy#7]
use an ORM

**Comment by ktakattack** [comment]
Discord number is the unique key. 
User is registered and then flag them as "active."
User has the ability to create, update.

**Comment by ktakattack** [comment]
start with "start" command and using library

**Comment by smartclash** [comment]
Merged https://github.com/csr/discord-coffee-buddy/pull/9. This issue is half done.

**Comment by ktakattack** [comment]
Next step, work on meetings model (create, store, etc.)

**Comment by ktakattack** [comment]
Meetings model merged per #14 . Working on meetingsService.
